# Generated by Django 3.2.9 on 2022-03-03 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petid', models.AutoField(primary_key=True, serialize=False)),
                ('petname', models.CharField(max_length=64)),
                ('pettype', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')], max_length=4)),
                ('breed', models.CharField(max_length=128)),
                ('age_year', models.IntegerField()),
                ('age_month', models.IntegerField()),
                ('birthday', models.DateField()),
                ('neutered', models.BooleanField()),
                ('petowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetPostImages',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=posts.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='PetPost',
            fields=[
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('closed', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='petimg', to='posts.petpostimages')),
                ('petid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='posts.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.petpost')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
