# Generated by Django 3.2.9 on 2022-03-03 05:15

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=posts.models.upload_to, verbose_name='Image'),
        ),
    ]
