# Generated by Django 3.2.9 on 2022-03-06 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.petpost'),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('userid', 'postid')},
        ),
    ]
