# Generated by Django 3.2.9 on 2022-02-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='postid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
