# Generated by Django 3.2.9 on 2022-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220306_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2),
        ),
    ]
