# Generated by Django 3.2.9 on 2022-03-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_petpostimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petpost',
            name='petid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.pet'),
        ),
    ]
