# Generated by Django 3.2.9 on 2022-03-29 00:23

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_pet_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petpost',
            name='image',
        ),
        migrations.CreateModel(
            name='PetPostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=posts.models.upload_to, verbose_name='Image')),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.petpost')),
            ],
        ),
    ]
