# Generated by Django 3.2.9 on 2022-04-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_pet_petowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hairlength',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=4),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(default=10),
        ),
    ]
