# Generated by Django 4.0.2 on 2022-02-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('username', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('addressLine1', models.CharField(max_length=256)),
                ('addressLine2', models.CharField(max_length=256)),
                ('zipcode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
