# Generated by Django 3.2.9 on 2022-04-02 16:01

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userprofilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(blank=True, default=None, upload_to=authentication.models.upload_to, verbose_name='profilePhoto'),
        ),
    ]
