# Generated by Django 3.2.9 on 2022-04-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='gender',
            field=models.CharField(default='N', max_length=4),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='hairlength',
            field=models.CharField(default='N', max_length=4),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
